name: 'Tests: Playground Matrix'

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run php-actions/composer@v6
      uses: php-actions/composer@v6
      with:
        php_version: "8.2"
        php_extensions: intl
        version: 2.x
    - uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        version: "10.1"
        php_version: "8.2"
        php_extensions: xdebug
        coverage_clover: clover.xml
        coverage_text: true
    - name: Make code coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.1
      with:
        coverage_badge_path: output/coverage.svg
        push_badge: false
    - name: Git push to testing/develop branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./output
        publish_branch: testing/develop
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
    - name: Slack notification
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C068A06PV43'
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Status:*\n${{ job.status }}/"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Pipeline:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow>"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

